Add validation for the version
The validation checks that the version is taggable using git.

For this, we need to use an image that has git so might as well use
Shipyard's image which already has git (anbd a bunch of other things).

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

diff --git a/scripts/lib/yaml_funcs b/scripts/lib/yaml_funcs
--- a/scripts/lib/yaml_funcs
+++ b/scripts/lib/yaml_funcs
@@ -1,7 +1,10 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 function printerr() {
-    printf "ERROR: %s\n" "$*" >&2
+    local err_msg="$*"
+
+    [[ -z "${file}" ]] || err_msg+=" (${file})"
+    printf "ERROR: %s\n" "${err_msg}" >&2
 }
 
 function get_value() {
@@ -17,7 +20,7 @@ function validate_value() {
     local value=$(get_value $file $key | tr -d [:space:])
 
     if [[ -z "$value" ]]; then
-        printerr "Missing value for '${key}' in ${file}"
+        printerr "Missing value for ${key@Q}"
         return 1
     fi
 }
